apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: gcr.io/predictmachines/alexey_nginx:latest
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: simapp-secrets-frontend
          ports:
          - containerPort: 80
            hostPort: 8080
          resources: {}
      imagePullSecrets:
        - name: gcr-access-token
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 146.148.121.11
